name: BetterKeepInventory
version: '${project.version}'
main: com.johnnykitty9.betterkeepinventory.betterkeepinventory.BetterKeepInventory
api-version: 1.18
authors: [ johnnykitty9 ]
description: Keep inventory but when someone dies to a player they drop their loot.
